-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.client (client_id serial NOT NULL,
                                                           "user" serial NOT NULL,
                                                                         client_sold double precision NOT NULL,
                                                                                                      name text COLLATE pg_catalog."default" NOT NULL,
                                                                                                                                             description text COLLATE pg_catalog."default",
                                                                                                                                                                      address text COLLATE pg_catalog."default",
                                                                                                                                                                                           telephone text COLLATE pg_catalog."default",
                                                                                                                                                                                                                  CONSTRAINT client_pkey PRIMARY KEY (client_id));


CREATE TABLE IF NOT EXISTS public.client_payment (payment_id serial NOT NULL,
                                                                    "user" serial NOT NULL,
                                                                                  client serial NOT NULL,
                                                  work serial NOT NULL, date date NOT NULL,
                                                                                  sum integer NOT NULL,
                                                                                              CONSTRAINT client_payment_pkey PRIMARY KEY (payment_id));


CREATE TABLE IF NOT EXISTS public.color (color_id serial NOT NULL,
                                                         name text COLLATE pg_catalog."default" NOT NULL,
                                                                                                material_type text COLLATE pg_catalog."default" NOT NULL,
                                                                                                                                                active boolean NOT NULL,
                                                                                                                                                               dimension integer[], rotable boolean NOT NULL,
                                                                                                                                                                                                    img_url text COLLATE pg_catalog."default" NOT NULL,
                                                                                                                                                                                                                                              CONSTRAINT color_pkey PRIMARY KEY (color_id));


CREATE TABLE IF NOT EXISTS public.created_item (item_id serial NOT NULL,
                                                               name text COLLATE pg_catalog."default" NOT NULL,
                                                                                                      material text COLLATE pg_catalog."default" NOT NULL,
                                                                                                                                                 qty integer NOT NULL,
                                                                                                                                                             size integer[] NOT NULL,
                                                                                                                                                                            "position" integer[] NOT NULL,
                                                                                                                                                                                                 rotation integer[] NOT NULL,
                                                                                                                                                                                                                    color serial NOT NULL,
                                                                                                                                                                                                                                 rotable boolean NOT NULL,
                                                                                                                                                                                                                                                 object serial NOT NULL,
                                                                                                                                                                                                                                                               CONSTRAINT created_item_pkey PRIMARY KEY (item_id));


CREATE TABLE IF NOT EXISTS public.object (object_id serial NOT NULL,
                                          work serial NOT NULL,
                                                      "user" serial NOT NULL,
                                                                    client serial NOT NULL,
                                                                                  name text COLLATE pg_catalog."default",
                                                                                                    used_script serial NOT NULL,
                                                                                                                       used_colors text[] COLLATE pg_catalog."default",
                                                                                                                                                  CONSTRAINT object_pkey PRIMARY KEY (object_id));


CREATE TABLE IF NOT EXISTS public.script (script_id serial NOT NULL,
                                                           name text COLLATE pg_catalog."default" NOT NULL,
                                                                                                  "user" serial NOT NULL,
                                                                                                                img_url text COLLATE pg_catalog."default",
                                                                                                                                     CONSTRAINT script_pkey PRIMARY KEY (script_id));


CREATE TABLE IF NOT EXISTS public.script_item (item_id serial NOT NULL,
                                                              script_id serial NOT NULL,
                                                                               name text COLLATE pg_catalog."default" NOT NULL,
                                                                                                                      material text COLLATE pg_catalog."default" NOT NULL,
                                                                                                                                                                 qty integer, size integer[] NOT NULL,
                                                                                                                                                                                             "position" integer[] NOT NULL,
                                                                                                                                                                                                                  rotation integer[] NOT NULL,
                                                                                                                                                                                                                                     CONSTRAINT script_item_pkey PRIMARY KEY (item_id));


CREATE TABLE IF NOT EXISTS public.users (user_id serial NOT NULL,
                                                        name text COLLATE pg_catalog."default" NOT NULL,
                                                                                               address text COLLATE pg_catalog."default",
                                                                                                                    telephone text COLLATE pg_catalog."default",
                                                                                                                                           username text COLLATE pg_catalog."default" NOT NULL,
                                                                                                                                                                                      sold double precision NOT NULL,
                                                                                                                                                                                                            CONSTRAINT user_pkey PRIMARY KEY (user_id));


CREATE TABLE IF NOT EXISTS public.user_payment (payment_id serial NOT NULL,
                                                                  "user" serial NOT NULL, date date NOT NULL,
                                                                                                    sum integer NOT NULL,
                                                                                                                CONSTRAINT user_payment_pkey PRIMARY KEY (payment_id));


CREATE TABLE IF NOT EXISTS public.work (work_id serial NOT NULL,
                                                       "user" serial NOT NULL,
                                                                     client serial NOT NULL,
                                                                                   name text COLLATE pg_catalog."default",
                                                                                                     status text COLLATE pg_catalog."default" NOT NULL,
                                                                                                                                              price integer NOT NULL,
                                                                                                                                                            paid integer NOT NULL,
                                                                                                                                                                         measure_date date, order_date date, finish_date date, CONSTRAINT work_pkey PRIMARY KEY (work_id));


ALTER TABLE IF EXISTS public.client ADD CONSTRAINT "user"
FOREIGN KEY ("user") REFERENCES public.users (user_id) MATCH SIMPLE ON
UPDATE NO ACTION ON
DELETE NO ACTION NOT VALID;


ALTER TABLE IF EXISTS public.client_payment ADD CONSTRAINT client
FOREIGN KEY (client) REFERENCES public.client (client_id) MATCH SIMPLE ON
UPDATE NO ACTION ON
DELETE NO ACTION NOT VALID;


ALTER TABLE IF EXISTS public.client_payment ADD CONSTRAINT "user"
FOREIGN KEY ("user") REFERENCES public.users (user_id) MATCH SIMPLE ON
UPDATE NO ACTION ON
DELETE NO ACTION NOT VALID;


ALTER TABLE IF EXISTS public.client_payment ADD CONSTRAINT
work
FOREIGN KEY (
             work) REFERENCES public.work (work_id) MATCH SIMPLE ON
UPDATE NO ACTION ON
DELETE NO ACTION NOT VALID;


ALTER TABLE IF EXISTS public.created_item ADD CONSTRAINT object
FOREIGN KEY (object) REFERENCES public.object (object_id) MATCH SIMPLE ON
UPDATE NO ACTION ON
DELETE NO ACTION NOT VALID;


ALTER TABLE IF EXISTS public.object ADD CONSTRAINT client
FOREIGN KEY (client) REFERENCES public.client (client_id) MATCH SIMPLE ON
UPDATE NO ACTION ON
DELETE NO ACTION NOT VALID;


ALTER TABLE IF EXISTS public.object ADD CONSTRAINT used_script
FOREIGN KEY (used_script) REFERENCES public.script (script_id) MATCH SIMPLE ON
UPDATE NO ACTION ON
DELETE NO ACTION NOT VALID;


ALTER TABLE IF EXISTS public.object ADD CONSTRAINT "user"
FOREIGN KEY ("user") REFERENCES public.users (user_id) MATCH SIMPLE ON
UPDATE NO ACTION ON
DELETE NO ACTION NOT VALID;


ALTER TABLE IF EXISTS public.object ADD CONSTRAINT
work
FOREIGN KEY (
             work) REFERENCES public.work (work_id) MATCH SIMPLE ON
UPDATE NO ACTION ON
DELETE NO ACTION NOT VALID;


ALTER TABLE IF EXISTS public.script_item ADD CONSTRAINT script
FOREIGN KEY (script_id) REFERENCES public.script (script_id) MATCH SIMPLE ON
UPDATE NO ACTION ON
DELETE NO ACTION NOT VALID;


ALTER TABLE IF EXISTS public.user_payment ADD CONSTRAINT "user"
FOREIGN KEY ("user") REFERENCES public.users (user_id) MATCH SIMPLE ON
UPDATE NO ACTION ON
DELETE NO ACTION NOT VALID;


ALTER TABLE IF EXISTS public.work ADD CONSTRAINT client
FOREIGN KEY (client) REFERENCES public.client (client_id) MATCH SIMPLE ON
UPDATE NO ACTION ON
DELETE NO ACTION NOT VALID;


ALTER TABLE IF EXISTS public.work ADD CONSTRAINT "user"
FOREIGN KEY ("user") REFERENCES public.users (user_id) MATCH SIMPLE ON
UPDATE NO ACTION ON
DELETE NO ACTION NOT VALID;

END;